#!/bin/bash

NOCOLOR='\033[0m'
RED='\033[1;31m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'

ERROR () {
  echo -e "${RED}ERROR${NOCOLOR}"
  exit
}

DONE () {
  echo -e "${GREEN}DONE${NOCOLOR}"
  sleep 1
}

if [[ $EUID -ne 0 ]]
then
	echo -e "${RED}Debe ejecutarse como usuario con privilegios (sudo ./cambonos-mkiso)${NOCOLOR}"
	exit
fi

echo -e "${BLUE}>>Carpeta destino ISO:${NOCOLOR}\c"
read -e -i $(pwd) RUTAD

echo -e "${BLUE}\n>>Instalando paquetes necesarios${NOCOLOR}"
sleep 2
pacman --noconfirm -Sy archiso && DONE || ERROR

echo -e "${BLUE}\n>>Creando ficheros de configuracion de la ISO${NOCOLOR}"
rm -rf /iso
mkdir -p /iso/perfil
cp -rv /usr/share/archiso/configs/releng/* /iso/perfil || ERROR
rm /iso/perfil/efiboot/loader/entries/02*
rm /iso/perfil/efiboot/loader/entries/03*
echo -e "neovim\ngit\nnetworkmanager\ndialog" >>/iso/perfil/packages.x86_64
cp -rv iso/* /iso/perfil || ERROR
cd /tmp
git clone https://github.com/CambonOS/installer.git
if [[ $1 = "-t" ]]
then
	sed -i "s/iso_version=\"\$(date +%Y.%m.%d)\"/iso_version=\"$2\"/" /iso/perfil/profiledef.sh
	cd installer
	git checkout tags/$2
	cd ..
fi
cp -rv installer /iso/perfil/airootfs/root/
rm -rf installer
git clone https://github.com/Cambon18/xfce.git
if [[ $1 = "-t" ]]
then
	cd xfce
	git checkout tags/$2
	cd ..
fi
cp -rv xfce /iso/perfil/airootfs/root/
rm -rf xfce
git clone https://github.com/Cambon18/qtile.git
if [[ $1 = "-t" ]]
then
	cd qtile
	git checkout tags/$2
	cd ..
fi
cp -rv qtile /iso/perfil/airootfs/root/
rm -rf qtile
cd /iso/perfil/airootfs/root
echo -e "while true\ndo\n\tping -c 2 archlinux.org && break\n\tsystemctl start NetworkManager.service\n\tsleep 5\n\tnmtui connect\ndone" > .zshrc
if [[ $1 = "-b" ]]
then
	sed -i "s/iso_version=\"\$(date +%Y.%m.%d)\"/iso_version=\"$2\"/" /iso/perfil/profiledef.sh
	echo -e "\nrm -rf installer xfce qtile\ngit clone -b $2 https://github.com/cambonos/installer\ngit clone https://github.com/Cambon18/xfce.git\ngit clone https://github.com/Cambon18/qtile.git" >> .zshrc
fi
echo -e 'sh installer/dialog.sh; if [[ $(cat /tmp/FIN_ERR) -eq 1 ]]; then dialog --title " CambonOS Installer " --msgbox "\nHa ocurrido un error en la instalación, se va a reiniciar el equipo.\nRetire el USB y pulse ENTER" 7 80; else dialog --title " CambonOS Installer " --msgbox "\nEl instalador ha finalizado\nRetire el USB y pulse ENTER" 7 80; fi; reboot' >> .zshrc
DONE

echo -e "${BLUE}\n>>Creando la ISO${NOCOLOR}"
sleep 2; cd
mkarchiso -v -w /iso/work -o $RUTAD /iso/perfil && DONE || ERROR

echo -e "${BLUE}\n>>Eliminado ficheros/paquetes innecesarios${NOCOLOR}"
sleep 2
rm -rf /iso
pacman --noconfirm -Rns archiso
DONE
